apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultra-ingress
  namespace: vaultra
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: vaultra-cert
spec:
  rules:
    - host: api.vaultra.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
    - host: vaultra.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
